// Participant phrases for the workers' council animation
// Edit this file to customize the phrases spoken by participants

const participantPhrases = [
  "Das sehe ich anders...",
  "Können wir abstimmen?",
  "Da bin ich dafür!",
  "Ich habe einen Vorschlag.",
  "Das müssen wir klären.",
  "Wie ist die Rechtslage?",
  "Das ist im Interesse der Mitarbeiter.",
  "Die Geschäftsführung sagt...",
  "Laut Paragraph...",
  "Wir sollten das vertagen.",
  "Dazu gibt es eine Umfrage.",
  "Das protokollieren wir.",
  "Wir müssen agil reagieren!",
  "Lassen Sie uns das disruptiv angehen.",
  "Die Zahlen sprechen für sich.",
  "Als Digital Native sehe ich das...",
  "Let's think outside the box!",
  "Haben wir dafür die Ressourcen?",
  "Wir brauchen mehr Synergien.",
  "Das ist nicht DSGVO-konform!",
  "Bei der Konkurrenz macht man das anders.",
  "Wo ist der Business Case?",
  "Was sagt der Compliance Officer?",
  "Lasst uns das im Deep Dive analysieren.",
  "Hier fehlt der Proof of Concept.",
  "Können wir das skalieren?",
  "Das ist nicht Teil der Roadmap!",
  "Einfach mal machen statt quatschen.",
  "Wir müssen den Stakeholdern zuhören.",
  "Ist das im Budget eingeplant?",
  "Das steht nicht in meiner OKR-Liste.",
  "Gibt es dafür eine Best Practice?",
  "Wir brauchen einen Paradigmenwechsel.",
  "Die KPIs sprechen dagegen.",
  "Ist das überhaupt nachhaltig?",
  "Das müssen wir noch mal benchmarken.",
  "Wir sollten eine Task Force gründen.",
  "Das müssen wir ganzheitlich betrachten.",
  "Ich setze auf Customer Centricity.",
  "Maximale Transparenz ist entscheidend.",
  "Wir brauchen ein Mindset-Shift!",
  "Haben wir dafür eine Blockchain-Lösung?",
  "Das war in meinem letzten Design Sprint anders.",
  "Lass uns das im Workshop vertiefen.",
  "Das ist ein echter Game Changer!",
  "Haben wir die Pain Points identifiziert?",
  "Das skaliert nicht exponentiell genug.",
  "Lasst uns einen Hackathon organisieren.",
  "Was sagt unsere AI dazu?",
  "Können wir das Minimum Viable Product definieren?",
  "Ich stelle das mal in den Parking Lot.",
  "Da fehlt mir die Customer Journey.",
  "Wir sollten das agil mit SCRUM umsetzen.",
  "Können wir das Feature togglen?",
  "Das müssen wir A/B testen.",
  "Die User Experience leidet darunter.",
  "Wir sollten mobile first denken.",
  "Dafür brauchen wir ein Cross-Functional Team.",
  "Das ist nicht DSGVO-compliant.",
  "Lasst uns das in der Retrospektive besprechen.",
  "Das steht nicht in den OKRs für dieses Quartal.",
  "Ist das CI/CD-Pipeline-ready?",
  "Ich habe das mal gewhiteboardet...",
  "Haben wir das in der Cloud?",
  "Wo ist der Single Point of Truth?",
  "Wer ist der Product Owner dafür?",
  "Was ist unser Unique Selling Point hier?",
  "Das müssen wir end-to-end durchdenken.",
  "Können wir Artificial Intelligence einsetzen?",
  "Bietet das einen wirklichen Mehrwert?",
  "Wir sollten unser Silo-Denken überwinden.",
  
  // Hitzige Ausrufe und Streit-Phrasen
  "Das ist kompletter Unsinn!",
  "So kommen wir nie zu einem Ergebnis!",
  "Jetzt reicht es mir aber!",
  "Ich werde das so nicht unterschreiben!",
  "Da müssen Sie mich falsch verstanden haben!",
  "Das können Sie doch nicht ernst meinen!",
  "Sie widersprechen sich permanent!",
  "Das habe ich von Anfang an gesagt!",
  "Moment mal, so war das nicht abgesprochen!",
  "Das ist absolut inakzeptabel!",
  "Ich lasse mich hier nicht unterbrechen!",
  "Diese Diskussion führt zu nichts!",
  "Das ist doch lächerlich!",
  "Wir drehen uns im Kreis!",
  "Mit Verlaub, das ist Schwachsinn!",
  "Ich protestiere entschieden!",
  "Das ist ein klarer Verstoß gegen die Vereinbarung!",
  "Ich bin fassungslos!",
  "Das werden wir so nicht akzeptieren!",
  "Ich will das im Protokoll festhalten!",
  "Hören Sie endlich auf, mich zu unterbrechen!",
  "Wir sollten zur Sachlichkeit zurückkehren!",
  "Das grenzt an Arbeitsverweigerung!",
  "Sie verdrehen die Tatsachen!",
  "Das ist doch Augenwischerei!",
  "Wir müssen die Reißleine ziehen!",
  "Da platzt mir gleich der Kragen!",
  "Das ist eine Farce!",
  "Ich fordere einen Beschluss hierzu!",
  "Das ist außerhalb Ihrer Kompetenz!",
  "Wer hat das denn entschieden?",
  "Seit wann machen wir das so?",
  "Das kann doch wohl nicht wahr sein!",
  "Ich erhebe formellen Einspruch!",
  "Das ist eine Unterstellung!"
];

// Normale Diskussionsphrasen
const discussionPhrases = [
  "Wir müssen die KPIs überprüfen",
  "Lass uns das offline besprechen",
  "Ich stelle das in den Parkplatz",
  "Wir brauchen mehr Synergien",
  "Das ist nicht in meinem Zuständigkeitsbereich",
  "Können wir das priorisieren?",
  "Ich bin damit einverstanden",
  "Wir sollten agiler vorgehen",
  "Haben wir dafür Budget?",
  "Ich muss das mit meinem Team abstimmen",
  "Lasst uns einen Workshop dazu machen",
  "Bitte alle ins Boot holen",
  "Wir sollten das eskalieren",
  "Können wir ein Follow-up vereinbaren?",
  "Das ist eine Win-win-Situation"
];

// Schrei-Phrasen (werden in Großbuchstaben angezeigt)
const shoutingPhrases = [
  "Das ist inakzeptabel",
  "Wir haben keine Zeit mehr",
  "Das hätte schon letzte Woche fertig sein sollen",
  "Das können wir uns nicht leisten",
  "Die Deadline ist morgen",
  "Das ist nicht, was ich bestellt habe",
  "Wir verlieren Kunden",
  "Die Zahlen stimmen nicht",
  "Niemand hat mich informiert",
  "Das kann nicht dein Ernst sein",
  "Wer ist dafür verantwortlich",
  "Das ist ein Desaster"
];

// Create a unified meetingPhrases object to make it easier to access all phrases
const meetingPhrases = {
  normalPhrases: discussionPhrases,
  shoutingPhrases: shoutingPhrases,
  participantPhrases: Array(10).fill(participantPhrases)
}; 